# Check the documentation at https://goreleaser.com for more options
version: 2
builds:
  - id: notation-local-signer
    main: ./cmd/notation-local-signer
    binary: notation-local-signer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
release:
  prerelease: auto
  draft: true
signs:
  - cmd: notation
    signature: "${artifact}.cose.sig"
    args:
      - "blob"
      - "sign"
      - "--plugin=local-signer"
      - "--id=localsigner"
      - "--plugin-config=certificate_bundle_path=./notation.crt"
      - "--signature-format=cose"
      - "--signature-directory=./dist"
      - "${artifact}"
    artifacts: all
    env:
      - LOCAL_SIGNER_SIGNING_KEY: "{{ .Env.LOCAL_SIGNER_SIGNING_KEY }}"
      - LOCAL_SIGNER_SIGNING_KEY_PASSWORD: "{{ .Env.LOCAL_SIGNER_SIGNING_KEY_PASSWORD }}"
