name: release-github

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true
      - name: setup Notation CLI
        uses: notaryproject/notation-action/setup@v1
        with:
          versin: v1.3.1
      - name: Install Notatio AKV plugin
        run: |
          notation plugin install \
            --url https://github.com/JeyJeyGao/notation-local-signer/releases/download/v0.1.2/notation-local-signer_0.1.2_linux_amd64.tar.gz \
            --sha256sum 2d99e434d4d9535acbac2e6812251e8c8454103b7a1d45189cd3cb455cf6cd5f
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          distribution: goreleaser
          version: v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCAL_SIGNER_SIGNING_KEY: ${{ secrets.LOCAL_SIGNER_SIGNING_KEY }}
          LOCAL_SIGNER_SIGNING_KEY_PASSWORD: ${{ secrets.LOCAL_SIGNER_SIGNING_KEY_PASSWORD }}